### ISSUE TITLE
Doesn't work with latest version of Guszzle.

### ISSUE THREAD

**Issue by masterjus** [leanphp/behat-code-coverage#14]
We're using Guzzle and it's latest version. And we also don't need remote debug. So strict requirement prevents us to use this extension.

**Comment by ek9** [comment]
I have released 2 new versions of this extension today:
- `v3.1.0` - uses `guzzlehttp/guzzle ~4.0||~5.0`. This is legacy support release, mostly for those still stuck with `4.0` or `5.0` for whatever reason. This version will not likely to receive further updates, but can be used for transition period. It is temporarily maintained on `v3.1` branch.
- `v3.2.0` - uses `guzzlehttp/guzzle ~6.0`. This will be maintained and will receive any updates (`master` branch).

I have also made an issue to gather more feedback regarding making `guzzlehttp/guzzle` optional altogether, as it is only required when using Remote Xdebug. Please check #15 and provide any additional feedback if you like.

As there is a version of this package that supports most recent guzzle versions (from `4.0 to 6.0`), I believe I can close this issue. Please let me know if there is something else.

Thank you for feedback.

**Comment by masterjus** [comment]
thanks a lot
