### ISSUE TITLE
Optional Code Coverage Generation

### ISSUE THREAD

**Issue by golovetska** [leanphp/behat-code-coverage#17]
Now we generate code coverage every time when execute `bin/behat` command. 
Is it possible to add some option to the command for code coverage?
Is there maybe some other workaround which could help me to generate code coverage not every time I run ` bin/behat` command?

**Comment by golovetska** [comment]
For now I've solved this problem by creating one more configuration file `behat-coverage.yml`. When I want to run behat with coverage I add `--config behat-coverage.yml` to the behat command.

**Comment by dannylewis-sheffield** [comment]
Pull request created to add --coverage https://github.com/leanphp/behat-code-coverage/pull/24

Usage:
bin/behat --coverage

Without coverage:
bin/behat
